language: python

python:
  - "3.6"

before_install:
  - pip install pep8

install:
  - pip install -r src/app/requirements.txt

script:
  - coverage run --source="src/" -m pytest
  - coverage report --fail-under=20
  - find . -name \*.py -exec pep8 --ignore={E402, E501} +

after_success: coveralls
