language: python

python:
  - "3.6"

before_install:
  - pip install pep8

install:
  - pip install -r src/app/requirements.txt

script:
  - coverage run -m pytest src/tests/
  - coverage report --include src/tests/ --fail-under=20
  - find . -name \*.py -exec pep8 --ignore=E402{} +

after_success: coveralls
