sudo: required

services:
  - docker

install:
  - sudo apt-get install -y linux-image-virtual kernel linux-image-extra-virtual
  - curl -sSL https://get.docker.com/ | sudo sh
  - sudo pip install docker-compose

script:
  - docker-compose up -d --build
  - docker exec app coverage run --source="src/app" -m pytest
  - docker exec app coverage report --fail-under=50
  - docker exec app pycodestyle src/ --ignore=E501,E402

#before_install:
#  - pip install pycodestyle
#
#install:
#  - pip install -r src/app/requirements.txt
#
#before_script:
#  - psql -c "CREATE DATABASE db_sskey;" -U postgres
#
#script:
#  - coverage run --source="src/app" -m pytest
#  - coverage report --fail-under=50
#  - pycodestyle src/ --ignore=E501,E402
