language: python

python:
  - "3.6"

services:
  - postgresql

before_install:
  - pip install pycodestyle

install:
  - pip install -r src/app/requirements.txt

before_script:

script:
  - coverage run --source="src/app" -m pytest
  - coverage report --fail-under=20
  - pycodestyle src/ --ignore=E501,E402
