env:
  DOCKER_COMPOSE_VERSION=3

before_install:
  - sudo apt-get update

  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine

  - docker-compose --version

  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

  - docker-compose --version

  - docker-compose up -d --build
  - docker exec app coverage run --source="src/app" -m pytest
  - docker exec app coverage report --fail-under=50
  - docker exec app pycodestyle src/ --ignore=E501,E402

  - docker ps
