language: python

python:
  - "3.6"

before_install:
  - pip install pycodestyle

install:
  - pip install -r src/app/requirements.txt

before_script:
  - pycodestyle src/

script:
  - coverage run --source="src/app" -m pytest
  - coverage report --fail-under=20

after_success: coveralls
