version: '3'

services:
  app:
    build: ./src
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:10.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_sskey
    ports:
      - "5432:5432"
